import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import styled from "styled-components";
const inter = Inter({ subsets: ["latin"] });

const Wrapper = styled.div`
  padding: 4em;
  background: papayawhip;
`;

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Wrapper>
          <Link href="/converter">Go to converter</Link>
          <Link href="/watchlist">Go to currencies list</Link>
        </Wrapper>
      </main>
    </>
  );
}
