import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import styled from "styled-components";
import { MainNavigation, Wrapper } from "@/styles/styled";
const inter = Inter({ subsets: ["latin"] });

const MainWrapper = styled(Wrapper)`
  padding-top: 7rem;
`;

export default function Home() {
  return (
    <MainWrapper>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <MainNavigation>
          <Link href="/converter">Go to converter</Link>
          <Link href="/watchlist">Go to currencies list</Link>
        </MainNavigation>
      </main>
    </MainWrapper>
  );
}
